### PR TITLE
Enable wheel support

### LINKED ISSUE #292: Support wheel packaging
It would be nice to offer a wheel package for model_mommy releases.
See http://pythonwheels.com/

### PR DESCRIPTION
**Pull request by orf**
Closes #292

### CODE REVIEW

**Comment by berinhard** [comment]
Thanks @orf! But could you change this PR to be merged into `develop` branch instead of `master`?

**Comment by orf** [comment]
Done :+1:

**Comment by berinhard** [comment]
@orf I'm not very familiarized with `wheel` yet. Could you explain me how can I test it to make sure it's working? Maybe we should add something on `tox.ini` file?

**Comment by orf** [comment]
Hey Berinhard, there is no need to test it I don't think. `wheel` is just a format for distribution that has some advantages over the standard `sdist` (basically just a .tar.gz with the source).

When pushing a new release all you need to do is run `setup.py sdist bdist_wheel upload` and a `sdist` + `wheel` will be created and uploaded. The `wheel` will be automatically downloaded by `pip` where possible, else the `source-dist` will be chosen.

**Comment by berinhard** [comment]
@vandersonmota so I'm merging the PR but I'll let to you to run the command:

```
python setup.py sdist bdist_wheel upload
```

**Comment by tdruez** [comment]
@vandersonmota @berinhard could one of you guys publish the wheel for 1.3.1? Thanks :)

**Pull request merged**
