### PR TITLE
Introducing: BinaryField filling

### LINKED ISSUE #212: Support for the BinaryField
Hey, it'd be cool if model-mommy would support django's BinaryField out of the box. The code I currently use to generate random binary data is:

    def gen_byte_string(s):
        return lambda: bytes(random.randint(0, 255) for x in range(s))

(Edit: I updated the algorithm).

### PR DESCRIPTION
**Pull request by Matt3o12**
This adds support for `BinaryField`s and thus closes #212.

### CODE REVIEW

**Comment by Matt3o12** [comment]
Thanks for pointing out and fixed :+1:

**Comment by Matt3o12** [comment]
Now I remember why I added that line. Django>1.6 testrunner appreantly looks for all classes in `BinaryFieldsFilling` and expect them to exist. If they don't, [it'll fail](https://travis-ci.org/vandersonmota/model_mommy/jobs/55315915#L125):

    AttributeError: 'module' object has no attribute 'BinaryFieldsFilling'

I could also rebase the last 2 commits if you want (so that there aren't 2 commits that do nothing).

**Comment by Matt3o12** [comment]
When are you going to merge the request and push it to pypi?

**Comment by vandersonmota** [comment]
Sorry about the delay @Matt3o12 
I will close this PR, but i cherrypicked the first two commits.

Thank you!

**Comment by Matt3o12** [comment]
Thanks :+1:

**Pull request closed without merging**
