### PR TITLE
Enable defining prepare generator as attribute of (custom) make gener…

### PR DESCRIPTION
**Pull request by katakumpo**
Maybe this can get an accept faster than the other one.
It could also solve https://github.com/vandersonmota/model_mommy/issues/241
Please tell me what you think :)

### CODE REVIEW

**Comment by vandersonmota** [comment]
sorry @katakumpo i was a little bit swamped last week. I'll look into this until the weekend.

Cheers

**Comment by bh** [comment]
:+1: Cool pull request, @katakumpo!

**Comment by katakumpo** [comment]
Hi there, any idea when you will have time to look at it? :)

**Comment by vandersonmota** [comment]
Dammit, sorry pal. @berinhard could you take a look at it?

**Comment by berinhard** [comment]
for sure

**Comment by berinhard** [comment]
@katakumpo i've just merged it. thanks for your help!

**Comment by vandersonmota** [comment]
thank you all @berinhard and @katakumpo

**Comment by katakumpo** [comment]
hey nice...thank you :)

**Pull request merged**
