### PR TITLE
Pass custom parameters to `save` method

### PR DESCRIPTION
**Pull request by berinhard**
Fixes: #278

### CODE REVIEW

**Comment by vandersonmota** [comment]
ugh, sorry @berinhard - https://github.com/vandersonmota/model_mommy/pull/290 introduced merge conflicts. Can you solve them?

I'll own you a beer

**Comment by berinhard** [comment]
I thought this would happen @vandersonmota! I can handle the conflicts without any problem and I'll remember of this beer next PythonSudeste =)

**Comment by berinhard** [comment]
@vandersonmota conflicts solved and travis is passing. Can I merge it?

**Comment by vandersonmota** [comment]
:+1:

**Pull request merged**
