### PR TITLE
Handle Django 1.9 rename

### PR DESCRIPTION
**Pull request by jschneier**
My test suite passes with this but not all of model_mommy's does. Thanks @petkostas for the guidance.

### CODE REVIEW

**Comment by jschneier** [comment]
Interestingly my tox report shows breakages on a bunch of Django's and I don't think it's my code change.

```  
py27-django14: commands succeeded
py27-django15: commands succeeded
py27-django16: commands succeeded
ERROR:   py27-django17: commands failed
ERROR:   py27-django18: commands failed
py26-django14: commands succeeded
py26-django15: commands succeeded
py26-django16: commands succeeded
py34-django15: commands succeeded
py34-django16: commands succeeded
ERROR:   py34-django17: commands failed
ERROR:   py34-django18: commands failed
ERROR:   py34-django19: commands failed
```
I don't have 3.3 or 3.5 installed.

**Comment by jschneier** [comment]
All the latest ones that is.

**Comment by vandersonmota** [comment]
hi @jschneier 
thanks for taking your time to help our project. =)

But Django 1.9 related stuff is already fixed at the development branch.

Looking forward for future contributions. =)

**Comment by jschneier** [comment]
Ah, I didn't realize you had a separate development branch for doing dev....my apologies.

**Comment by jschneier** [comment]
Any idea why you are going to release to pypi?

**Comment by vandersonmota** [comment]
Released today. =)

**Pull request closed without merging**
