### PR TITLE
Allow Models with an attribute named 'model' to be used in mommy.make

### PR DESCRIPTION
**Pull request by jdunck**
For #333

### CODE REVIEW

**Comment by jdunck** [comment]
Sure, I can change - you OK w an amended commit?

**Comment by berinhard** [comment]
@jdunck no, feel free to add new commits instead of amending.

**Comment by jdunck** [comment]
@berinhard PR updated - I added a changelog note and bumped the version also.  The commit broke on one CI permutation but I think that's noise?  Is it possible to retrigger to verify the build?

**Comment by berinhard** [comment]
@jdunck the tests in CI seem to be failing. Could you take a look? Another thing, could you undo the version bump and rename the changelog category `1.5.0` to `Development`?

**Comment by jdunck** [comment]
@berinhard Yes, all CI builds are passing except for one - and looking at that, it seems to be a network failure installing dependencies:

```
cmdargs: ['/home/travis/build/vandersonmota/model_mommy/.tox/py35-django18-postgresql/bin/pip', 'install', 'Pillow>=2.3.1', 'mock==1.0.1', 'six>=1.3.0', 'django-test-without-migrations', 'Django>=1.8,<1.9', 'psycopg2']

Collecting Pillow>=2.3.1
  Downloading Pillow-4.3.0-cp35-cp35m-manylinux1_x86_64.whl (5.8MB)
...  File "/opt/python/3.5.3/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
...
pip._vendor.requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

ERROR: could not install deps [Pillow>=2.3.1, mock==1.0.1, six>=1.3.0, django-test-without-migrations, Django>=1.8,<1.9, psycopg2]; v = InvocationError('/home/travis/build/vandersonmota/model_mommy/.tox/py35-django18-postgresql/bin/pip install Pillow>=2.3.1 mock==1.0.1 six>=1.3.0 django-test-without-migrations Django>=1.8,<1.9 psycopg2 (see /home/travis/build/vandersonmota/model_mommy/.tox/py35-django18-postgresql/log/py35-django18-postgresql-1.log)', 2)
```

Could you re-trigger the build?  I don't think this failure is related to my changes.  I'll fix the changelog and maybe that also will be enough to pass. ;)

**Comment by jdunck** [comment]
Thanks :)

**Pull request merged**
