### PR TITLE
Generators refactoring

### PR DESCRIPTION
**Pull request by berinhard**
I really advice this pull request to be reviewed commit by commit instead of just looking the complete diff.

There are a few refactoring points in this pr:
- Encapsulation of complex login in `Mommy._make` method;
- Extraction of generator functions to a new file;
- Creation of a new `generators.py` to prepare a viable path to the API proposed by #275;
- Generating values for IP, M2M and FKs were moved to generator logic and removed from `model_mommy/mommy.py`

### CODE REVIEW

**Comment by berinhard** [comment]
@vandersonmota this refactoring breaks support for Django 1.5 because of `IPAddressField`. In my opnion, we could drop support for this version because not even Django supports it anymore. What do you think?

**Comment by vandersonmota** [comment]
@berinhard i'm cool with that.

**Comment by berinhard** [comment]
@vandersonmota I tried to do it with this [commit](https://github.com/vandersonmota/model_mommy/pull/291/commits/aed19b13cb3afd2537311d023c09cd609a48e59b), but I don't know if TravisCI keeps a custom or specific `tox.ini` file because Django 1.5 tests seems to keep running.

**Comment by vandersonmota** [comment]
@berinhard check the `travis.yml` file

**Pull request merged**
