### PR TITLE
Recipe.prepare does not save related recipes

### PR DESCRIPTION
**Pull request by codingjoe**
You can call `Recipe.prepare` on a model with a ForeignKey and if
you don't have defined a `foreign_key`-recipe the related object
will not be persited. However if you define a related recipe the
related object will be persistet.

Besides that behavior being inconsistent, there really is no reason
and it presents disadvantages.

This patch solves the issue, by using the `_save_realted` attribute
that is already existing but not used for related objects in recipes.

### CODE REVIEW

**Comment by codingjoe** [comment]
@vandersonmota any thoughts on this?

**Comment by vandersonmota** [comment]
sorry @codingjoe about the delay. It looks pretty good to me. Can you make the PR against `development` branch?

**Comment by codingjoe** [comment]
@vandersonmota no problem. I rebased and changed the target.

**Comment by vandersonmota** [comment]
thanks a lot!

**Comment by codingjoe** [comment]
@vandersonmota any changes there will be a `1.4.0` release soon?

**Pull request merged**
