### PR TITLE
Fix wrong method calling

### PR DESCRIPTION
**Pull request by novelview9**
Fix wrong method calling
In origin code was
from datetime import datetime
and calling datetime.date (actually it is datetime.datetime.date)
so datetime.date is not the method which making date objects, but get date from datetime object

### CODE REVIEW

**Comment by novelview9** [comment]
?

**Comment by vandersonmota** [comment]
@novelview9 care to solve the conflicts, please?

**Comment by novelview9** [comment]
oh, you've changed base branch!
All done.

**Comment by vandersonmota** [comment]
Thanks @novelview9

**Pull request merged**
