### PR TITLE
Enable separate generator definitions

### PR DESCRIPTION
**Pull request by katakumpo**
This is based on https://github.com/vandersonmota/model_mommy/pull/250
It would be nice if you can have a look at it :)

### CODE REVIEW

**Comment by vandersonmota** [comment]
@katakumpo i'm wondering in which scenarios a different generator for make and prepare is desired. Could you give an example.
Cheers

**Comment by katakumpo** [comment]
An example are ForeignKey and OneToOneField generators. I built a custom ForeignKey to overcome django's restriction of always making IntegerFields when the relatead Field is an AutoField.
I used it to get tinyint and smallint as autofilled pk and the referenced  table gets the same type.
Thats where i can't just add a make generator that works for prepare.

**Comment by katakumpo** [comment]
as i remember my thoughts where something like this:

An alternative to this would have been to edit def prepare(self) to check for isinstance, but that looks like a hack imo, because why not just allow seperate definitions for all fields and have make and prepare beeing completely generic.

**Comment by katakumpo** [comment]
closing it in favour for #254

**Pull request closed without merging**
